"""empty message

Revision ID: 7735bb5abece
Revises: 8622e76b2e9b
Create Date: 2021-02-24 13:22:19.744741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7735bb5abece'
down_revision = '8622e76b2e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('rating', sa.Integer(), nullable=True))
    op.drop_column('post', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('likes', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('comment', 'rating')
    # ### end Alembic commands ###
