"""empty message

Revision ID: 158e282cbb7f
Revises: bd8b5ddba5f8
Create Date: 2021-02-22 11:59:51.976808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158e282cbb7f'
down_revision = 'bd8b5ddba5f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Forename', sa.String(length=15), nullable=False))
    op.add_column('user', sa.Column('Surname', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'Surname')
    op.drop_column('user', 'Forename')
    # ### end Alembic commands ###
