"""empty message

Revision ID: 506a709d6ee7
Revises: 6f30717f7454
Create Date: 2021-02-25 15:33:58.610808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506a709d6ee7'
down_revision = '6f30717f7454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourite')
    # ### end Alembic commands ###
